import { createClient } from '@supabase/supabase-js';

// Load and sanitize Supabase configuration
const cleanEnvVar = (val: string): string => {
  let cleaned = (val || '').trim();
  // Strip starting/ending quotes if present (e.g. "https://..." or 'https://...')
  if ((cleaned.startsWith('"') && cleaned.endsWith('"')) || (cleaned.startsWith("'") && cleaned.endsWith("'"))) {
    cleaned = cleaned.slice(1, -1).trim();
  }
  return cleaned;
};

const rawUrl = import.meta.env.VITE_SUPABASE_URL || '';
const rawKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

const supabaseUrl = cleanEnvVar(rawUrl).replace(/\/$/, ''); // Remove trailing slashes
const supabaseAnonKey = cleanEnvVar(rawKey);

export const isSupabaseConfigured = Boolean(
  supabaseUrl && 
  supabaseAnonKey && 
  supabaseUrl !== 'https://your-supabase-project.supabase.co' && 
  supabaseAnonKey !== 'your-anon-public-key'
);

// Safe console diagnostics to help debug without exposing secret keys
console.log('=== Supabase Config Diagnostics ===', {
  isConfigured: isSupabaseConfigured,
  hasUrl: !!supabaseUrl,
  urlSample: supabaseUrl ? (supabaseUrl.length > 15 ? supabaseUrl.substring(0, 15) + '...' : supabaseUrl) : 'none',
  urlLength: supabaseUrl ? supabaseUrl.length : 0,
  hasKey: !!supabaseAnonKey,
  keyLength: supabaseAnonKey ? supabaseAnonKey.length : 0,
  viteKeys: Object.keys(import.meta.env).filter(k => k.startsWith('VITE_'))
});

// Gracefully initialize Supabase client or fallback to placeholder strings to prevent typescript null errors
const finalUrl = isSupabaseConfigured && supabaseUrl ? supabaseUrl : 'https://placeholder-project-id.supabase.co';
const finalKey = isSupabaseConfigured && supabaseAnonKey ? supabaseAnonKey : 'placeholder-anon-key';

export const supabase = createClient(finalUrl, finalKey);

// Simulated storage handlers for when Supabase is not configured yet
export const getSimulatedData = <T>(key: string): T[] => {
  const data = localStorage.getItem(`supabase_sim_${key}`);
  return data ? JSON.parse(data) : [];
};

export const saveSimulatedData = <T>(key: string, item: T): void => {
  const current = getSimulatedData<T>(key);
  localStorage.setItem(`supabase_sim_${key}`, JSON.stringify([item, ...current]));
};

// SQL helper pattern for tables creation
export const SQL_SETUP_SCRIPT = `-- EXECUTE ESTE SCRIPT NO EDITOR SQL DO SEU PAINEL SUPABASE:

-- 1. Tabela de Mensagens de Contato
CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  telefone TEXT,
  mensagem TEXT,
  data TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela de Propostas / Orçamentos
CREATE TABLE IF NOT EXISTS quote_requests (
  id TEXT PRIMARY KEY,
  condominio_nome TEXT NOT NULL,
  endereco TEXT,
  unidades INTEGER,
  contato_nome TEXT NOT NULL,
  contato_email TEXT NOT NULL,
  contato_telefone TEXT,
  cargo TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela de Reservas de Lazer
CREATE TABLE IF NOT EXISTS bookings (
  id TEXT PRIMARY KEY,
  area TEXT NOT NULL,
  data TEXT NOT NULL,
  periodo TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabela de Ocorrências / Chamados
CREATE TABLE IF NOT EXISTS tickets (
  id TEXT PRIMARY KEY,
  categoria TEXT NOT NULL,
  titulo TEXT NOT NULL,
  descricao TEXT,
  data_criacao TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabela de Perfis de Usuários
CREATE TABLE IF NOT EXISTS perfis (
  id UUID PRIMARY KEY,
  auth_user_id UUID NOT NULL,
  nome TEXT NOT NULL,
  cpf TEXT,
  email TEXT NOT NULL,
  unidade TEXT,
  tipo TEXT NOT NULL, -- administrador, colaborador, sindico, etc.
  perfil TEXT, -- fallback/alias
  data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar acesso público de escrita nas tabelas para habilitar leads via formulários do site
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir inserções públicas" ON contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir leitura pública temporária" ON contact_messages FOR SELECT USING (true);

ALTER TABLE quote_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir inserções públicas" ON quote_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir leitura pública temporária" ON quote_requests FOR SELECT USING (true);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo para simulação" ON bookings FOR ALL USING (true);

ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo para simulação" ON tickets FOR ALL USING (true);

ALTER TABLE perfis ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo para simulação de perfis" ON perfis FOR ALL USING (true);
`;
